version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.docker
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Frontend.docker
    ports:
      - "3001:80"
    depends_on:
      - backend
    restart: always
